#!/usr/bin/env node
/**
 * Turn a validated Viewer Recipe into a standalone, minimal repo: the
 * generic engine and globe wrapper (viewer/src/core/, viewer/src/globe/),
 * no dev tooling, no private submodule, no local copy of data -- everything
 * else comes from the recipe's own dataHost at runtime. See
 * docs/plans/consider-this-general-question-virtual-kay.md.
 *
 *   node generator/scaffoldRepo.mjs recipe.json outDir [validateSource] [--update [--force]]
 *
 * Generated Sites update by regeneration (docs/adr/0055): every file this
 * writes is recorded, with its hash and the Geode version that wrote it, in
 * the site's .geode/generated.json. `--update` regenerates an existing site
 * in place, and refuses if any recorded file was edited by hand since --
 * those edits would be lost -- unless `--force`, which also adopts a site
 * generated before stamps existed. Files the site added itself are never
 * touched.
 */
import {
  readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync,
} from 'node:fs';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { validateRecipe } from './validateRecipe.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(HERE, '..');
const VIEWER_ROOT = path.join(REPO_ROOT, 'viewer');

function loadJson(p) {
  return JSON.parse(readFileSync(p, 'utf8'));
}

function escapeHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** `multiGlobe` is offered uniformly across all four wrapper types (see
 *  docs/adr/0022) -- one shared literal-emitter rather than four copies. */
function multiGlobeFieldTs(recipe) {
  return recipe.multiGlobe ? `\n  multiGlobe: ${JSON.stringify(recipe.multiGlobe)},` : '';
}

function configTs(recipe, resolved) {
  return `import type { GlobeTool, MultiGlobeConfig } from '../core/tools';

export interface GlobeConfig {
  modelId: string;
  title: string;
  tools: GlobeTool[];
  multiGlobe?: MultiGlobeConfig;
}

// Generated by generator/scaffoldRepo.mjs from this repo's own recipe.json --
// hand-edit that and re-run the generator rather than editing this file
// directly, or the two will silently disagree.
export const GLOBE_CONFIG: GlobeConfig = {
  modelId: ${JSON.stringify(resolved.modelId)},
  title: ${JSON.stringify(recipe.site.title)},
  tools: ${JSON.stringify(recipe.ui.tools)} as GlobeTool[],${multiGlobeFieldTs(recipe)}
};
`;
}

/** Fixed labels for model-group-globe's two axes -- v1.5 only ever
 *  compares along these two declared manifest fields (reconstruction_model,
 *  comparison_role), so the labels are fixed here rather than being a
 *  recipe field of their own. */
const AXIS_A_LABEL = 'reconstruction';
const AXIS_B_LABEL = 'role';

function groupConfigTs(recipe, resolved) {
  const gridLiteral = {};
  for (const a of resolved.axisA.values) {
    gridLiteral[a] = {};
    for (const b of resolved.axisB.values) gridLiteral[a][b] = resolved.grid[a][b].modelId;
  }
  return `import type { GlobeTool, MultiGlobeConfig } from '../core/tools';

export interface GroupGlobeConfig {
  title: string;
  tools: GlobeTool[];
  multiGlobe?: MultiGlobeConfig;
  axisALabel: string;
  axisBLabel: string;
  grid: Record<string, Record<string, string>>;
  defaultAxisA: string;
  defaultAxisB: string;
}

// Generated by generator/scaffoldRepo.mjs from this repo's own recipe.json --
// hand-edit that and re-run the generator rather than editing this file
// directly, or the two will silently disagree.
export const GROUP_GLOBE_CONFIG: GroupGlobeConfig = {
  title: ${JSON.stringify(recipe.site.title)},
  tools: ${JSON.stringify(recipe.ui.tools)} as GlobeTool[],${multiGlobeFieldTs(recipe)}
  axisALabel: ${JSON.stringify(AXIS_A_LABEL)},
  axisBLabel: ${JSON.stringify(AXIS_B_LABEL)},
  grid: ${JSON.stringify(gridLiteral, null, 2)},
  defaultAxisA: ${JSON.stringify(resolved.defaultAxisA)},
  defaultAxisB: ${JSON.stringify(resolved.defaultAxisB)},
};
`;
}

function reconstructionConfigTs(recipe, resolved) {
  return `import type { MultiGlobeConfig } from '../core/tools';

export interface ReconstructionConfig {
  reconstructionId: string;
  title: string;
  multiGlobe?: MultiGlobeConfig;
}

// Generated by generator/scaffoldRepo.mjs from this repo's own recipe.json --
// hand-edit that and re-run the generator rather than editing this file
// directly, or the two will silently disagree.
export const RECONSTRUCTION_CONFIG: ReconstructionConfig = {
  reconstructionId: ${JSON.stringify(resolved.reconstruction.id)},
  title: ${JSON.stringify(recipe.site.title)},${multiGlobeFieldTs(recipe)}
};
`;
}

function reconstructionGroupConfigTs(recipe, resolved) {
  return `import type { MultiGlobeConfig } from '../core/tools';

export interface ReconstructionGroupConfig {
  title: string;
  multiGlobe?: MultiGlobeConfig;
  reconstructionIds: string[];
  anchorPlates?: Record<string, number>;
}

// Generated by generator/scaffoldRepo.mjs from this repo's own recipe.json --
// hand-edit that and re-run the generator rather than editing this file
// directly, or the two will silently disagree.
export const RECONSTRUCTION_GROUP_CONFIG: ReconstructionGroupConfig = {
  title: ${JSON.stringify(recipe.site.title)},${multiGlobeFieldTs(recipe)}
  reconstructionIds: ${JSON.stringify(resolved.entries.map((e) => e.id))},${
  recipe.anchorPlates ? `\n  anchorPlates: ${JSON.stringify(recipe.anchorPlates)},` : ''}
};
`;
}

function mantleConfigTs(recipe, resolved) {
  const m = recipe.mantle ?? {};
  const config = {
    title: recipe.site.title,
    models: resolved.models.map((x) => x.id),
    defaultModel: resolved.defaultModel,
    ...(m.defaultCamera ? { defaultCamera: m.defaultCamera } : {}),
    ...(m.viewPresets ? { viewPresets: m.viewPresets } : {}),
    ...(m.comparisonPresets !== undefined ? { comparisonPresets: m.comparisonPresets } : {}),
  };
  // The interface is copied from the checked-in viewer/src/generated/
  // mantleConfig.ts, so the two can't drift.
  const src = readFileSync(path.join(VIEWER_ROOT, 'src', 'generated', 'mantleConfig.ts'), 'utf8');
  const types = src.slice(0, src.indexOf('/**\n * The file generator/scaffoldRepo.mjs'));
  return `${types}// Generated by generator/scaffoldRepo.mjs from this repo's own recipe.json --
// edit that and regenerate (--update) rather than editing this file.
export const MANTLE_CONFIG: MantleConfig = ${JSON.stringify(config, null, 2)};
`;
}

function packageJson(site, viewerPkg) {
  return `${JSON.stringify({
    name: site.repoName,
    private: true,
    version: '1.0.0',
    type: 'module',
    scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
    dependencies: {
      three: viewerPkg.dependencies.three,
      'lil-gui': viewerPkg.dependencies['lil-gui'],
    },
    devDependencies: {
      vite: viewerPkg.devDependencies.vite,
      typescript: viewerPkg.devDependencies.typescript,
      '@types/three': viewerPkg.devDependencies['@types/three'],
    },
  }, null, 2)}\n`;
}

function viteConfigTs() {
  return `import { defineConfig } from 'vite';

// GitHub Pages serves a project site under /<repo>/, not the domain root --
// VITE_BASE is set by the deploy workflow below, from the repo's own name,
// so this works unmodified whatever the site was named. Do not hardcode a
// path here (see the main Geode repo's own vite.config.ts for why).
export default defineConfig({
  base: process.env.VITE_BASE ?? '/',
  server: { port: 5173 },
  build: {
    target: 'es2022',
    // three.js alone accounts for most of this and isn't meaningfully
    // tree-shakeable here -- the whole rendering pipeline is used, and a
    // single-view WebGL app has no route-based split point. Raised rather
    // than chased: Vite's default 500 kB warning assumes a splittable app,
    // which this genuinely isn't.
    chunkSizeWarningLimit: 700,
    rollupOptions: {
      output: {
        // Name the three/lil-gui chunk explicitly rather than letting
        // Rollup pick one of the app modules bundled alongside it, and
        // split it from app code so a code-only redeploy doesn't
        // invalidate the browser's cached copy of three.js.
        manualChunks(id) {
          if (id.includes('node_modules')) return 'vendor';
        },
      },
    },
  },
});
`;
}

function tsconfigJson() {
  return `${JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      lib: ['ES2022', 'DOM', 'DOM.Iterable'],
      strict: true,
      noEmit: true,
      skipLibCheck: true,
      esModuleInterop: true,
      allowSyntheticDefaultImports: true,
      isolatedModules: true,
      // core/boundaries.ts imports the vendored petrify JS library
      // (no .d.ts of its own) -- without this, `tsc --noEmit` fails on
      // that file even in a repo whose wrapperType never imports it,
      // since `include` below type-checks everything under src/ whether
      // or not anything actually imports it. Matches this monorepo's own
      // viewer/tsconfig.json.
      allowJs: true,
      types: ['vite/client'],
    },
    include: ['src'],
  }, null, 2)}\n`;
}

function deployWorkflowYml(dataHost) {
  const release = dataHost.release;
  const fetchStep = release ? `
      # This site's Archive is a release asset on this repo (docs/adr/0054),
      # unpacked beside the app; Vite copies public/ into dist/.
      - name: Fetch the Archive
        env:
          GH_TOKEN: \${{ github.token }}
        run: |
          mkdir -p public/archive
          gh release download ${release.tag} --repo "$GITHUB_REPOSITORY" \\
            --pattern ${release.asset} --output - | tar -xz -C public/archive
          test -f public/archive/archive.json \\
            || { echo "::error::release ${release.tag} has no ${release.asset} with an archive.json at its root"; exit 1; }
` : '';
  const buildEnv = release ? '' : `\n          VITE_ARCHIVE_BASE: ${dataHost.archiveBase}`;
  return `# Build and publish to GitHub Pages. Generated by Geode's viewer generator --
# see recipe.json in this repo's root for what was requested and
# https://github.com/siwill22/Geode for the tool that built it.
#
${release
    ? `# The data is this repo's own release asset ${release.tag}/${release.asset}, a
# standalone Archive, unpacked into the site at build time.`
    : `# Unlike a hand-built Geode viewer, this repo has no local data of its own:
# every page load fetches live from the shared archive below, so there is
# nothing to download or unpack at build time, and no private submodule.`}
name: Deploy

on:
  push:
    branches: [main]
${release ? `  # Run with "gh workflow run deploy.yml" after publishing a new Archive
  # release: nothing else redeploys the site when only the data changes.
` : ''}  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
${fetchStep}
      - run: npm ci
      - run: npm run build
        env:
          VITE_BASE: /\${{ github.event.repository.name }}/${buildEnv}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
`;
}

function dataSectionMd(recipe, resolved) {
  if (recipe.wrapperType === 'mantle-globe') {
    return resolved.models.map((m) => `- **${m.name}** (\`${m.id}\`)\n  - Source: ${m.source || "see the model's own manifest"}`).join('\n') + '\n';
  }
  if (recipe.wrapperType === 'single-model-globe') {
    const coastlineNote = resolved.coastlines.source === 'none'
      ? 'This site has no reconstructed coastline overlay.'
      : `Coastlines are reconstructed against ${resolved.coastlines.reconstructionModel ?? 'the shared plate model'}.`;
    return `- **${resolved.modelName}** (\`${resolved.modelId}\`)\n`
      + `- Source: ${resolved.modelSource || "see the model's own manifest"}\n`
      + `- ${coastlineNote}\n`;
  }
  if (recipe.wrapperType === 'single-reconstruction-globe') {
    const r = resolved.reconstruction;
    const boundaryNote = r.hasBoundaries
      ? 'Includes resolved plate boundary topology (subduction zones, ridges, transforms).'
      : 'Coastlines only -- this Reconstruction Model has no resolved plate boundary topology '
        + '(see docs/adr/0019: some models genuinely never will).';
    return `- **${r.name}** (\`${r.id}\`)\n`
      + `- Source: ${r.source || "see the reconstruction's own manifest"}\n`
      + `- ${boundaryNote}\n`;
  }
  if (recipe.wrapperType === 'reconstruction-group-globe') {
    const lines = ['- Comparing Reconstruction Models (switch via dropdown):'];
    for (const e of resolved.entries) {
      lines.push(`  - **${e.name}** (\`${e.id}\`)${e.hasBoundaries ? '' : ' -- coastlines only, no boundary topology'}`);
    }
    return `${lines.join('\n')}\n`;
  }
  // model-group-globe: list every cell in the grid, grouped by axisA so a
  // reader can see the whole comparison at a glance.
  const lines = [`- Comparing by **${AXIS_A_LABEL}** (${resolved.axisA.values.join(', ')}) `
    + `x **${AXIS_B_LABEL}** (${resolved.axisB.values.join(', ')})`];
  for (const a of resolved.axisA.values) {
    for (const b of resolved.axisB.values) {
      const cell = resolved.grid[a][b];
      lines.push(`  - ${a} / ${b}: **${cell.modelName}** (\`${cell.modelId}\`)`);
    }
  }
  lines.push(`- Source: ${resolved.modelSource || "see each model's own manifest"}`);
  return `${lines.join('\n')}\n`;
}

function readmeMd(recipe, resolved) {
  const { site } = recipe;
  return `# ${site.title}

${site.description ?? ''}

Generated by [Geode](https://github.com/siwill22/Geode)'s viewer generator.
See \`recipe.json\` in this repo for exactly what was requested.

## Data

${dataSectionMd(recipe, resolved)}
${dataHostMd(recipe.dataHost)}
## Development

\`\`\`
${recipe.dataHost.release ? devWithReleaseMd(recipe.dataHost.release) : ''}npm install
npm run dev
\`\`\`

## Updating

This site was generated; see \`.geode/generated.json\` for the Geode version
that wrote it. To pick up a newer Geode, or a changed \`recipe.json\`, regenerate
from a Geode checkout rather than editing the generated files:

\`\`\`
node generator/scaffoldRepo.mjs path/to/this/recipe.json path/to/this/repo --update
\`\`\`

It refuses if a generated file was edited by hand, and names the file.

## License

The code in this repo is MIT-licensed (see \`LICENSE\`). The underlying
data remains under its own source's terms -- see the citation above.
`;
}

function dataHostMd(dataHost) {
  if (dataHost.release) {
    return `The data is a standalone Archive, published as this repo's release asset
\`${dataHost.release.tag}\` (\`${dataHost.release.asset}\`) and unpacked into the site
at deploy time, so the site doesn't depend on any other host. Each layer's
provenance is in the Archive's \`archive.json\` (\`sources\`), and each imported
Model's recorded import decisions are in \`models/<id>/ingest.json\`.
`;
  }
  return `Data is fetched live from ${dataHost.archiveBase} on every page load --
this repo carries no copy of it. If that catalog changes (a model is
updated, removed, or corrected), this site's behavior can change without a
redeploy of this repo.
`;
}

function devWithReleaseMd(release) {
  return `# once: the Archive, from this repo's release
mkdir -p public/archive
gh release download ${release.tag} --pattern ${release.asset} --output - | tar -xz -C public/archive
`;
}

function mitLicense() {
  const year = new Date().getFullYear();
  return `MIT License

Copyright (c) ${year}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to
deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
`;
}

/** Every file under `dir`, as [path relative to `dir`, contents]. */
function filesUnder(dir, prefix = '') {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const rel = path.posix.join(prefix, e.name);
    if (e.isDirectory()) out.push(...filesUnder(path.join(dir, e.name), rel));
    else out.push([rel, readFileSync(path.join(dir, e.name))]);
  }
  return out;
}

function sha256(buf) {
  return createHash('sha256').update(buf).digest('hex');
}

/** Which Geode wrote a site: the viewer's package version and the commit,
 *  flagged when the checkout had uncommitted changes. */
function geodeVersion(viewerPkg) {
  const git = (...args) => execFileSync('git', ['-C', REPO_ROOT, ...args], { encoding: 'utf8' }).trim();
  try {
    return { version: viewerPkg.version, commit: git('rev-parse', 'HEAD'),
      dirty: git('status', '--porcelain', '--', 'viewer/src', 'viewer/vendor', 'generator') !== '' };
  } catch {
    return { version: viewerPkg.version, commit: null, dirty: null };
  }
}

const STAMP = '.geode/generated.json';
/** The input, not an output: regenerating from an edited recipe is the
 *  point of --update, so it is never a hand edit to refuse over. */
const NOT_CHECKED = new Set(['recipe.json']);

/**
 * @param {string} recipePath
 * @param {string} outDir
 * @param {string} [validateSource] Local archive dir or http(s) URL to
 *   validate against, for this repo's own pre-release testing of a model
 *   not yet on the recipe's real dataHost (see validateRecipe.mjs's
 *   identical parameter), and required for a `dataHost.release` recipe,
 *   whose Archive isn't published until the site is. Never affects what's
 *   WRITTEN into the generated repo.
 * @param {{ update?: boolean, force?: boolean }} [opts]
 */
export async function scaffoldRepo(recipePath, outDir, validateSource, opts = {}) {
  const recipe = loadJson(path.resolve(recipePath));
  const result = await validateRecipe(recipe, validateSource);
  if (!result.ok) {
    throw new Error(`recipe is invalid, run validateRecipe.mjs first:\n${JSON.stringify(result.errors, null, 2)}`);
  }
  const { resolved } = result;

  // Which wrapper directory + HTML entry + generated/config filename this
  // recipe needs -- the only things that differ between wrapperTypes. Each
  // wrapper only ever depends on core/, never on another wrapper directory
  // (see core/tools.ts's doc comment), so exactly one of these gets copied.
  const WRAPPER_DIR = {
    'single-model-globe': 'globe',
    'model-group-globe': 'groupGlobe',
    'single-reconstruction-globe': 'reconstruction',
    'reconstruction-group-globe': 'reconstructionGroup',
    'mantle-globe': 'tomography',
  };
  const HTML_SOURCE = {
    'single-model-globe': 'globe.html',
    'model-group-globe': 'groupGlobe.html',
    'single-reconstruction-globe': 'reconstruction.html',
    'reconstruction-group-globe': 'reconstructionGroup.html',
    'mantle-globe': 'index.html',
  };
  const CONFIG_FILE = {
    'single-model-globe': 'config.ts',
    'model-group-globe': 'groupConfig.ts',
    'single-reconstruction-globe': 'reconstructionConfig.ts',
    'reconstruction-group-globe': 'reconstructionGroupConfig.ts',
    'mantle-globe': 'mantleConfig.ts',
  };
  const CONFIG_SOURCE = {
    'single-model-globe': configTs,
    'model-group-globe': groupConfigTs,
    'single-reconstruction-globe': reconstructionConfigTs,
    'reconstruction-group-globe': reconstructionGroupConfigTs,
    'mantle-globe': mantleConfigTs,
  };
  const wrapperDir = WRAPPER_DIR[recipe.wrapperType];
  const scriptSrc = `/src/${wrapperDir}/main.ts`;

  // Everything the site gets, before any of it is written.
  const files = new Map();
  const emit = (rel, content) => files.set(rel, Buffer.from(content));

  for (const [rel, buf] of filesUnder(path.join(VIEWER_ROOT, 'src', 'core'))) files.set(`src/core/${rel}`, buf);
  for (const [rel, buf] of filesUnder(path.join(VIEWER_ROOT, 'src', wrapperDir))) files.set(`src/${wrapperDir}/${rel}`, buf);
  // core/boundaries.ts imports the vendored petrify JS library
  // unconditionally (see that file) -- copied for every wrapperType, not
  // just the two that use it, so core/ never has a dangling import
  // regardless of which wrapper a future recipe adds it to. Dependency-free
  // and ~36 kB; not worth branching on.
  for (const [rel, buf] of filesUnder(path.join(VIEWER_ROOT, 'vendor', 'petrify', 'js'))) files.set(`vendor/petrify/js/${rel}`, buf);

  let html = readFileSync(path.join(VIEWER_ROOT, HTML_SOURCE[recipe.wrapperType]), 'utf8');
  html = html.replace(/<title>.*<\/title>/, `<title>${escapeHtml(recipe.site.title)}</title>`);
  html = html.replace(scriptSrc, `.${scriptSrc}`);
  emit('index.html', html);
  emit(`src/generated/${CONFIG_FILE[recipe.wrapperType]}`, CONFIG_SOURCE[recipe.wrapperType](recipe, resolved));

  const viewerPkg = loadJson(path.join(VIEWER_ROOT, 'package.json'));
  emit('package.json', packageJson(recipe.site, viewerPkg));
  emit('vite.config.ts', viteConfigTs());
  emit('tsconfig.json', tsconfigJson());
  emit('.github/workflows/deploy.yml', deployWorkflowYml(recipe.dataHost));
  emit('recipe.json', `${JSON.stringify(recipe, null, 2)}\n`);
  emit('README.md', readmeMd(recipe, resolved));
  emit('LICENSE', mitLicense());
  emit('.gitignore', `node_modules/\ndist/\n${recipe.dataHost.release ? 'public/archive/\n' : ''}`);
  if (recipe.dataHost.archiveBase) {
    // The same archive location the deploy workflow sets, so a local
    // `npm run build` produces the site that will actually ship -- without
    // it a local build falls back to /archive on its own origin, which such
    // a repo never has. Not a secret: the URL is public by design. A
    // release-hosted site has no .env: its Archive IS at /archive.
    emit('.env', `# Where this site's data lives -- same value the deploy workflow sets.\n`
      + `VITE_ARCHIVE_BASE=${recipe.dataHost.archiveBase}\n`);
  }

  // Regeneration (docs/adr/0055): refuse to overwrite hand edits.
  const stampPath = path.join(outDir, STAMP);
  const previous = existsSync(stampPath) ? loadJson(stampPath) : null;
  if (previous && !opts.update) {
    throw new Error(`${outDir} is already a generated site (${STAMP}); regenerate it with --update`);
  }
  if (opts.update && !previous && !opts.force) {
    // Sites generated before stamps existed: nothing records what was
    // generated, so nothing can be checked for hand edits. --force adopts
    // one, overwriting every file the generator writes.
    throw new Error(`${outDir} has no ${STAMP}: it predates stamps, or was not generated. `
      + `--update --force adopts it, overwriting every generated file (diff it in git first)`);
  }
  if (previous) {
    const edited = Object.entries(previous.files)
      .filter(([rel]) => !NOT_CHECKED.has(rel))
      .filter(([rel, hash]) => {
        const p = path.join(outDir, rel);
        return !existsSync(p) || sha256(readFileSync(p)) !== hash;
      })
      .map(([rel]) => rel);
    if (edited.length && !opts.force) {
      throw new Error(`these generated files were edited or removed by hand since `
        + `${previous.geode?.commit?.slice(0, 7) ?? 'the last generation'}, and --update would `
        + `overwrite them:\n  ${edited.join('\n  ')}\nMove the change into recipe.json (or Geode `
        + `itself), or pass --force to discard it.`);
    }
    // Generated before, not now (e.g. a file dropped from core/): remove it.
    for (const rel of Object.keys(previous.files)) {
      if (!files.has(rel)) rmSync(path.join(outDir, rel), { force: true });
    }
  }

  for (const [rel, buf] of files) {
    mkdirSync(path.dirname(path.join(outDir, rel)), { recursive: true });
    writeFileSync(path.join(outDir, rel), buf);
  }
  const stamp = {
    note: 'Written by Geode generator/scaffoldRepo.mjs. Regenerate with --update rather than editing the files listed here.',
    geode: geodeVersion(viewerPkg),
    wrapperType: recipe.wrapperType,
    files: Object.fromEntries([...files].map(([rel, buf]) => [rel, sha256(buf)]).sort()),
  };
  mkdirSync(path.dirname(stampPath), { recursive: true });
  writeFileSync(stampPath, `${JSON.stringify(stamp, null, 2)}\n`);

  return { outDir, resolved, changed: previous
    ? [...files].filter(([rel, buf]) => previous.files[rel] !== sha256(buf)).map(([rel]) => rel)
    : [...files.keys()] };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const flags = new Set(args.filter((a) => a.startsWith('--')));
  const [recipePath, outDir, validateSourceArg] = args.filter((a) => !a.startsWith('--'));
  if (!recipePath || !outDir || [...flags].some((f) => !['--update', '--force'].includes(f))) {
    console.error('usage: node generator/scaffoldRepo.mjs recipe.json outDir [validateSource] [--update [--force]]');
    process.exit(2);
  }
  const validateSource = validateSourceArg
    ? (/^https?:\/\//.test(validateSourceArg) ? validateSourceArg : path.resolve(validateSourceArg))
    : undefined;
  try {
    const { resolved, changed } = await scaffoldRepo(recipePath, path.resolve(outDir), validateSource,
      { update: flags.has('--update'), force: flags.has('--force') });
    console.log(`${flags.has('--update') ? 'updated' : 'scaffolded'} ${outDir} (${changed.length} file(s) written with new content)`);
    console.log(JSON.stringify(resolved, null, 2));
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
}
