#!/usr/bin/env node
/**
 * Turn a validated Viewer Recipe into a standalone, minimal repo: the
 * generic engine and globe wrapper (viewer/src/core/, viewer/src/globe/),
 * no dev tooling, no private submodule, no local copy of data -- everything
 * else comes from the recipe's own dataHost at runtime. See
 * docs/plans/consider-this-general-question-virtual-kay.md.
 *
 *   node generator/scaffoldRepo.mjs recipe.json outDir
 */
import {
  readFileSync, writeFileSync, mkdirSync, cpSync,
} from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { validateRecipe } from './validateRecipe.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(HERE, '..');
const VIEWER_ROOT = path.join(REPO_ROOT, 'viewer');

function loadJson(p) {
  return JSON.parse(readFileSync(p, 'utf8'));
}

function escapeHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** `multiGlobe` is offered uniformly across all four wrapper types (see
 *  docs/adr/0022) -- one shared literal-emitter rather than four copies. */
function multiGlobeFieldTs(recipe) {
  return recipe.multiGlobe ? `\n  multiGlobe: ${JSON.stringify(recipe.multiGlobe)},` : '';
}

function configTs(recipe, resolved) {
  return `import type { GlobeTool, MultiGlobeConfig } from '../core/tools';

export interface GlobeConfig {
  modelId: string;
  title: string;
  tools: GlobeTool[];
  multiGlobe?: MultiGlobeConfig;
}

// Generated by generator/scaffoldRepo.mjs from this repo's own recipe.json --
// hand-edit that and re-run the generator rather than editing this file
// directly, or the two will silently disagree.
export const GLOBE_CONFIG: GlobeConfig = {
  modelId: ${JSON.stringify(resolved.modelId)},
  title: ${JSON.stringify(recipe.site.title)},
  tools: ${JSON.stringify(recipe.ui.tools)} as GlobeTool[],${multiGlobeFieldTs(recipe)}
};
`;
}

/** Fixed labels for model-group-globe's two axes -- v1.5 only ever
 *  compares along these two declared manifest fields (reconstruction_model,
 *  comparison_role), so the labels are fixed here rather than being a
 *  recipe field of their own. */
const AXIS_A_LABEL = 'reconstruction';
const AXIS_B_LABEL = 'role';

function groupConfigTs(recipe, resolved) {
  const gridLiteral = {};
  for (const a of resolved.axisA.values) {
    gridLiteral[a] = {};
    for (const b of resolved.axisB.values) gridLiteral[a][b] = resolved.grid[a][b].modelId;
  }
  return `import type { GlobeTool, MultiGlobeConfig } from '../core/tools';

export interface GroupGlobeConfig {
  title: string;
  tools: GlobeTool[];
  multiGlobe?: MultiGlobeConfig;
  axisALabel: string;
  axisBLabel: string;
  grid: Record<string, Record<string, string>>;
  defaultAxisA: string;
  defaultAxisB: string;
}

// Generated by generator/scaffoldRepo.mjs from this repo's own recipe.json --
// hand-edit that and re-run the generator rather than editing this file
// directly, or the two will silently disagree.
export const GROUP_GLOBE_CONFIG: GroupGlobeConfig = {
  title: ${JSON.stringify(recipe.site.title)},
  tools: ${JSON.stringify(recipe.ui.tools)} as GlobeTool[],${multiGlobeFieldTs(recipe)}
  axisALabel: ${JSON.stringify(AXIS_A_LABEL)},
  axisBLabel: ${JSON.stringify(AXIS_B_LABEL)},
  grid: ${JSON.stringify(gridLiteral, null, 2)},
  defaultAxisA: ${JSON.stringify(resolved.defaultAxisA)},
  defaultAxisB: ${JSON.stringify(resolved.defaultAxisB)},
};
`;
}

function reconstructionConfigTs(recipe, resolved) {
  return `import type { MultiGlobeConfig } from '../core/tools';

export interface ReconstructionConfig {
  reconstructionId: string;
  title: string;
  multiGlobe?: MultiGlobeConfig;
}

// Generated by generator/scaffoldRepo.mjs from this repo's own recipe.json --
// hand-edit that and re-run the generator rather than editing this file
// directly, or the two will silently disagree.
export const RECONSTRUCTION_CONFIG: ReconstructionConfig = {
  reconstructionId: ${JSON.stringify(resolved.reconstruction.id)},
  title: ${JSON.stringify(recipe.site.title)},${multiGlobeFieldTs(recipe)}
};
`;
}

function reconstructionGroupConfigTs(recipe, resolved) {
  return `import type { MultiGlobeConfig } from '../core/tools';

export interface ReconstructionGroupConfig {
  title: string;
  multiGlobe?: MultiGlobeConfig;
  reconstructionIds: string[];
}

// Generated by generator/scaffoldRepo.mjs from this repo's own recipe.json --
// hand-edit that and re-run the generator rather than editing this file
// directly, or the two will silently disagree.
export const RECONSTRUCTION_GROUP_CONFIG: ReconstructionGroupConfig = {
  title: ${JSON.stringify(recipe.site.title)},${multiGlobeFieldTs(recipe)}
  reconstructionIds: ${JSON.stringify(resolved.entries.map((e) => e.id))},
};
`;
}

function packageJson(site, viewerPkg) {
  return `${JSON.stringify({
    name: site.repoName,
    private: true,
    version: '1.0.0',
    type: 'module',
    scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
    dependencies: {
      three: viewerPkg.dependencies.three,
      'lil-gui': viewerPkg.dependencies['lil-gui'],
    },
    devDependencies: {
      vite: viewerPkg.devDependencies.vite,
      typescript: viewerPkg.devDependencies.typescript,
      '@types/three': viewerPkg.devDependencies['@types/three'],
    },
  }, null, 2)}\n`;
}

function viteConfigTs() {
  return `import { defineConfig } from 'vite';

// GitHub Pages serves a project site under /<repo>/, not the domain root --
// VITE_BASE is set by the deploy workflow below, from the repo's own name,
// so this works unmodified whatever the site was named. Do not hardcode a
// path here (see the main Geode repo's own vite.config.ts for why).
export default defineConfig({
  base: process.env.VITE_BASE ?? '/',
  server: { port: 5173 },
  build: {
    target: 'es2022',
    // three.js alone accounts for most of this and isn't meaningfully
    // tree-shakeable here -- the whole rendering pipeline is used, and a
    // single-view WebGL app has no route-based split point. Raised rather
    // than chased: Vite's default 500 kB warning assumes a splittable app,
    // which this genuinely isn't.
    chunkSizeWarningLimit: 700,
    rollupOptions: {
      output: {
        // Name the three/lil-gui chunk explicitly rather than letting
        // Rollup pick one of the app modules bundled alongside it, and
        // split it from app code so a code-only redeploy doesn't
        // invalidate the browser's cached copy of three.js.
        manualChunks(id) {
          if (id.includes('node_modules')) return 'vendor';
        },
      },
    },
  },
});
`;
}

function tsconfigJson() {
  return `${JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      lib: ['ES2022', 'DOM', 'DOM.Iterable'],
      strict: true,
      noEmit: true,
      skipLibCheck: true,
      esModuleInterop: true,
      allowSyntheticDefaultImports: true,
      isolatedModules: true,
      // core/boundaries.ts imports the vendored petrify JS library
      // (no .d.ts of its own) -- without this, `tsc --noEmit` fails on
      // that file even in a repo whose wrapperType never imports it,
      // since `include` below type-checks everything under src/ whether
      // or not anything actually imports it. Matches this monorepo's own
      // viewer/tsconfig.json.
      allowJs: true,
      types: ['vite/client'],
    },
    include: ['src'],
  }, null, 2)}\n`;
}

function deployWorkflowYml(archiveBase) {
  return `# Build and publish to GitHub Pages. Generated by Geode's viewer generator --
# see recipe.json in this repo's root for what was requested and
# https://github.com/siwill22/Geode for the tool that built it.
#
# Unlike a hand-built Geode viewer, this repo has no local data of its own:
# every page load fetches live from the shared archive below, so there is
# nothing to download or unpack at build time, and no private submodule.
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci
      - run: npm run build
        env:
          VITE_BASE: /\${{ github.event.repository.name }}/
          VITE_ARCHIVE_BASE: ${archiveBase}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
`;
}

function dataSectionMd(recipe, resolved) {
  if (recipe.wrapperType === 'single-model-globe') {
    const coastlineNote = resolved.coastlines.source === 'none'
      ? 'This site has no reconstructed coastline overlay.'
      : `Coastlines are reconstructed against ${resolved.coastlines.reconstructionModel ?? 'the shared plate model'}.`;
    return `- **${resolved.modelName}** (\`${resolved.modelId}\`)\n`
      + `- Source: ${resolved.modelSource || "see the model's own manifest"}\n`
      + `- ${coastlineNote}\n`;
  }
  if (recipe.wrapperType === 'single-reconstruction-globe') {
    const r = resolved.reconstruction;
    const boundaryNote = r.hasBoundaries
      ? 'Includes resolved plate boundary topology (subduction zones, ridges, transforms).'
      : 'Coastlines only -- this Reconstruction Model has no resolved plate boundary topology '
        + '(see docs/adr/0019: some models genuinely never will).';
    return `- **${r.name}** (\`${r.id}\`)\n`
      + `- Source: ${r.source || "see the reconstruction's own manifest"}\n`
      + `- ${boundaryNote}\n`;
  }
  if (recipe.wrapperType === 'reconstruction-group-globe') {
    const lines = ['- Comparing Reconstruction Models (switch via dropdown):'];
    for (const e of resolved.entries) {
      lines.push(`  - **${e.name}** (\`${e.id}\`)${e.hasBoundaries ? '' : ' -- coastlines only, no boundary topology'}`);
    }
    return `${lines.join('\n')}\n`;
  }
  // model-group-globe: list every cell in the grid, grouped by axisA so a
  // reader can see the whole comparison at a glance.
  const lines = [`- Comparing by **${AXIS_A_LABEL}** (${resolved.axisA.values.join(', ')}) `
    + `x **${AXIS_B_LABEL}** (${resolved.axisB.values.join(', ')})`];
  for (const a of resolved.axisA.values) {
    for (const b of resolved.axisB.values) {
      const cell = resolved.grid[a][b];
      lines.push(`  - ${a} / ${b}: **${cell.modelName}** (\`${cell.modelId}\`)`);
    }
  }
  lines.push(`- Source: ${resolved.modelSource || "see each model's own manifest"}`);
  return `${lines.join('\n')}\n`;
}

function readmeMd(recipe, resolved) {
  const { site } = recipe;
  return `# ${site.title}

${site.description ?? ''}

Generated by [Geode](https://github.com/siwill22/Geode)'s viewer generator.
See \`recipe.json\` in this repo for exactly what was requested.

## Data

${dataSectionMd(recipe, resolved)}
Data is fetched live from ${recipe.dataHost.archiveBase} on every page load --
this repo carries no copy of it. If that catalog changes (a model is
updated, removed, or corrected), this site's behavior can change without a
redeploy of this repo.

## Development

\`\`\`
npm install
npm run dev
\`\`\`

## License

The code in this repo is MIT-licensed (see \`LICENSE\`). The underlying
data remains under its own source's terms -- see the citation above.
`;
}

function mitLicense() {
  const year = new Date().getFullYear();
  return `MIT License

Copyright (c) ${year}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to
deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
sell copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
`;
}

/**
 * @param {string} recipePath
 * @param {string} outDir
 * @param {string} [validateSource] Local archive dir or http(s) URL to
 *   validate against, for this repo's own pre-release testing of a model
 *   not yet on the recipe's real dataHost (see validateRecipe.mjs's
 *   identical parameter). Never affects what's WRITTEN into the generated
 *   repo -- VITE_ARCHIVE_BASE and the README always come from the
 *   recipe's own dataHost.archiveBase, since that's what will actually
 *   serve the deployed site.
 */
export async function scaffoldRepo(recipePath, outDir, validateSource) {
  const recipe = loadJson(path.resolve(recipePath));
  const result = await validateRecipe(recipe, validateSource);
  if (!result.ok) {
    throw new Error(`recipe is invalid, run validateRecipe.mjs first:\n${JSON.stringify(result.errors, null, 2)}`);
  }
  const { resolved } = result;

  // Which wrapper directory + HTML entry + generated/config filename this
  // recipe needs -- the only things that differ between wrapperTypes. Each
  // wrapper only ever depends on core/, never on another wrapper directory
  // (see core/tools.ts's doc comment), so exactly one of these gets copied.
  const WRAPPER_DIR = {
    'single-model-globe': 'globe',
    'model-group-globe': 'groupGlobe',
    'single-reconstruction-globe': 'reconstruction',
    'reconstruction-group-globe': 'reconstructionGroup',
  };
  const HTML_SOURCE = {
    'single-model-globe': 'globe.html',
    'model-group-globe': 'groupGlobe.html',
    'single-reconstruction-globe': 'reconstruction.html',
    'reconstruction-group-globe': 'reconstructionGroup.html',
  };
  const CONFIG_FILE = {
    'single-model-globe': 'config.ts',
    'model-group-globe': 'groupConfig.ts',
    'single-reconstruction-globe': 'reconstructionConfig.ts',
    'reconstruction-group-globe': 'reconstructionGroupConfig.ts',
  };
  const CONFIG_SOURCE = {
    'single-model-globe': configTs,
    'model-group-globe': groupConfigTs,
    'single-reconstruction-globe': reconstructionConfigTs,
    'reconstruction-group-globe': reconstructionGroupConfigTs,
  };
  const wrapperDir = WRAPPER_DIR[recipe.wrapperType];
  const htmlSource = HTML_SOURCE[recipe.wrapperType];
  const scriptSrc = `/src/${wrapperDir}/main.ts`;
  const configFileName = CONFIG_FILE[recipe.wrapperType];
  const configSource = CONFIG_SOURCE[recipe.wrapperType](recipe, resolved);

  mkdirSync(outDir, { recursive: true });
  mkdirSync(path.join(outDir, '.github', 'workflows'), { recursive: true });
  mkdirSync(path.join(outDir, 'src', 'generated'), { recursive: true });

  cpSync(path.join(VIEWER_ROOT, 'src', 'core'), path.join(outDir, 'src', 'core'), { recursive: true });
  cpSync(path.join(VIEWER_ROOT, 'src', wrapperDir), path.join(outDir, 'src', wrapperDir), { recursive: true });
  // core/boundaries.ts imports the vendored petrify JS library
  // unconditionally (see that file) -- copied for every wrapperType, not
  // just the two that use it, so core/ never has a dangling import
  // regardless of which wrapper a future recipe adds it to. Dependency-free
  // and ~36 kB; not worth branching on.
  mkdirSync(path.join(outDir, 'vendor', 'petrify', 'js'), { recursive: true });
  cpSync(
    path.join(VIEWER_ROOT, 'vendor', 'petrify', 'js'),
    path.join(outDir, 'vendor', 'petrify', 'js'),
    { recursive: true },
  );

  let html = readFileSync(path.join(VIEWER_ROOT, htmlSource), 'utf8');
  html = html.replace(/<title>.*<\/title>/, `<title>${escapeHtml(recipe.site.title)}</title>`);
  html = html.replace(scriptSrc, `.${scriptSrc}`);
  writeFileSync(path.join(outDir, 'index.html'), html);

  writeFileSync(path.join(outDir, 'src', 'generated', configFileName), configSource);

  const viewerPkg = loadJson(path.join(VIEWER_ROOT, 'package.json'));
  writeFileSync(path.join(outDir, 'package.json'), packageJson(recipe.site, viewerPkg));
  writeFileSync(path.join(outDir, 'vite.config.ts'), viteConfigTs());
  writeFileSync(path.join(outDir, 'tsconfig.json'), tsconfigJson());
  writeFileSync(
    path.join(outDir, '.github', 'workflows', 'deploy.yml'),
    deployWorkflowYml(recipe.dataHost.archiveBase),
  );

  writeFileSync(path.join(outDir, 'recipe.json'), `${JSON.stringify(recipe, null, 2)}\n`);
  writeFileSync(path.join(outDir, 'README.md'), readmeMd(recipe, resolved));
  writeFileSync(path.join(outDir, 'LICENSE'), mitLicense());
  writeFileSync(path.join(outDir, '.gitignore'), 'node_modules/\ndist/\n');

  return { outDir, resolved };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const [recipePath, outDir, validateSourceArg] = process.argv.slice(2);
  if (!recipePath || !outDir) {
    console.error('usage: node generator/scaffoldRepo.mjs recipe.json outDir [validateSource]');
    process.exit(2);
  }
  const validateSource = validateSourceArg
    ? (/^https?:\/\//.test(validateSourceArg) ? validateSourceArg : path.resolve(validateSourceArg))
    : undefined;
  const { resolved } = await scaffoldRepo(recipePath, path.resolve(outDir), validateSource);
  console.log(`scaffolded ${outDir}`);
  console.log(JSON.stringify(resolved, null, 2));
}
